### ISSUE TITLE
Issues if the container registry (serverURL) isn't just the hostname

### ISSUE THREAD

**Issue by simongottschlag** [chrismellard/docker-credential-acr-env#3]
Hi!

Thank you for the great work of maintaining this package. :1st_place_medal: 

I've been troubleshooting an issue with `cosign` when it comes to authenticating to the Azure Container Registry. One of the issues I've found is that somewhere along the way, the whole container image URL is passed to your helper and it causes the authentication to fail.

Reference for the method: https://github.com/chrismellard/docker-credential-acr-env/blob/fe33c00cee21eacc9fc67b6492b2c0cbe08b8bbe/pkg/credhelper/helper.go#L67

If we look at the same Elastic Container Registry (AWS) helper, we can clearly see them extracting information before passing it to their other functions: https://github.com/awslabs/amazon-ecr-credential-helper/blob/69c85dc22db6511932bbf119e1a0cc5c90c69a7f/ecr-login/ecr.go#L46

I'll create a PR for you to review.

Reference for the cosign issue: https://github.com/sigstore/cosign/issues/1350

**Comment by imjasonh** [comment]
Hi! 👋 

I added that code in #2 and I think I see the bug. I'll send a PR now.

**Comment by simongottschlag** [comment]
@imjasonh hi! 😊

I was actually experiencing the issue before using your patch. Or at least I think so. 🤔

**Comment by simongottschlag** [comment]
@imjasonh please take a look at the following before: https://github.com/chrismellard/docker-credential-acr-env/pull/4

**Comment by imjasonh** [comment]
> @imjasonh hi! 😊
> 
> I was actually experiencing the issue before using your patch. Or at least I think so. 🤔

Yep, I thought I was looking for a bug in `Get` when it looks like it's actually just the refresh token flow when repos are included. Completely missed your PR, which is _much_ better 😆

**Comment by simongottschlag** [comment]
@imjasonh Do you think we should still add this even tough we fixed it in `go-containerregistry`?

**Comment by imjasonh** [comment]
I'll leave that up to @chrismellard -- the normal way this code is called is with just the hostname and no path component, it was (seemingly) only due to a bug in that library's usage that it was being called in any other way. 

In the spirit of [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle) it might make sense to be more flexible in what this accepts, but I don't think we need it anymore, since we're doing the right thing now.

**Comment by simongottschlag** [comment]
Great! It's up to you @chrismellard :+1:
